include:
  - template: 'Workflows/Branch-Pipelines.gitlab-ci.yml'

stages:
  - p4_sim
  - bitfile
  - package
  - trigger_downstream

variables:
  GIT_STRATEGY: clone

.common:
  image: wharf.es.net/ht/xilinx-tools-docker:21087-g4c4c1a59
  tags:
    - ht-docker
  before_script:
    - source /opt/Xilinx/Vivado/2021.2/settings64.sh
  variables:
    XILINXD_LICENSE_FILE: "2100@dmv.es.net"
    # Required to keep click python module happy
    LC_ALL: C.UTF-8
    LANG: C.UTF-8
    GIT_SUBMODULE_STRATEGY: recursive

p4bm:
  stage: p4_sim
  extends: .common
  script:
    - apt update -y
    - apt install -y python3-setuptools
    - pip3 install scapy
    - make -C p4/sim build sim-all
  artifacts:
    name: "artifacts.$CI_PROJECT_NAME.$CI_JOB_NAME.$CI_PIPELINE_ID"
    paths:
      - p4/sim
  needs: []

build_bitfile:
  stage: bitfile
  extends: .common
  script:
    - make build BUILD_NAME=open-nic-ci
  artifacts:
    name: "artifacts.$CI_PROJECT_NAME.$CI_JOB_NAME.$CI_PIPELINE_ID"
    paths:
      - artifacts
      - esnet-smartnic-hw
    exclude:
      - .git/**
      - .git
      - .gitignore
      - .gitlab-ci.yml
      - .gitmodules
    when: always
    expire_in: 2 weeks
  timeout: 8h
  needs: []
  rules:
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
    - if: '$CI_COMMIT_BRANCH != $CI_DEFAULT_BRANCH'
      when: manual
      allow_failure: true

export_hwapi:
  stage: package
  extends: .common
  before_script: []
  script:
    - unzip artifacts/open-nic-ci/artifacts.esnet-smartnic-hw.export_hwapi.0.zip
  artifacts:
    name: "artifacts.$CI_PROJECT_NAME.$CI_JOB_NAME.$CI_PIPELINE_ID"
    paths:
      - esnet-smartnic-hwapi
    when: always
    expire_in: 3 month
  timeout: 30m
  needs:
    - build_bitfile
  rules:
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
    - if: '$CI_COMMIT_BRANCH != $CI_DEFAULT_BRANCH'
      when: manual
      allow_failure: true

trigger_downstream_job:
  stage: trigger_downstream
  variables:
    SN_HW_GROUP: $CI_PROJECT_NAMESPACE
    SN_HW_REPO: $CI_PROJECT_NAME
    SN_HW_BRANCH: $CI_COMMIT_BRANCH

  trigger:
    project: ht/esnet-smartnic-fw
    branch: main
  rules:
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
